module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontSize: {
        xs: "12px",
        sm: "14px",
        base: "16px",
        lg: "18px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "28px",
        "4xl": "32px",
        "5xl": "36px",
      },
      spacing: {
        0.5: "2px",
        1: "4px",
        1.5: "6px",
        2: "8px",
        2.5: "10px",
        3: "12px",
        3.5: "14px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px",
        11: "44px",
        12: "48px",
        14: "56px",
        16: "64px",
        20: "80px",
        24: "96px",
      },
      borderWidth: {
        0.25: "1px",
      },
      borderRadius: {
        md: "6px",
        DEFAULT: "4px",
      },
      colors: {
        primary: "#FFB800",
        secondary: "#F2F4F7",
        gray: {
          2: "#78829D",
          4: "#F5F5F5",
        },
        black: "#252F4A",
        warning: "#EC940E",
        info: "#176CDD",
        success: "#07AF17",
        error: "#F01919",
        button: "#F9F9F9",
        input: "#DBDFE9",
      },
      width: {
        "15ch": "15ch",
      },
    },
  },
  plugins: [],
  prefix: "tw-",
  important: ".antd-calendar",
};
